name: CI Pipeline

on:
  push:
    branches: [ "prd" ]
  pull_request:
    branches: [ "prd" ]

env:
  ENVIRONMENT: ${{ vars.ENVIRONMENT  }}
  ADMIN_USERNAME: ${{ secrets.TEST_ADMIN_USERNAME }}
  ADMIN_PASSWORD: ${{ secrets.TEST_ADMIN_PASSWORD }}
  IS_TEST: True

jobs:
  security_gates:
    name: Analize estatica e de dependencias
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: configurar python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Instala dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.security.txt

      - name: Security Gate 1 - SCA
        run: pip-audit -r requirements.txt

      - name: Security Gate 2 - SAST
        run: bandit -r app/ -c bandit.yaml -lll -iii

  unit-tests:
    name: Executa Pytest
    runs-on: ubuntu-latest
    needs: security_gates
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: configurar python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Instala dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements.test.txt

      - name: Executar testes
        run: |
          python3 -m pytest -v